source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'

require 'httparty'
gem 'pg'
gem 'puma'
gem 'rake'
gem 'pry'
gem 'dotenv'
gem 'sinatra-cross_origin'

group :test do
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'rack-test'
  gem 'rspec'
  gem 'vcr'
  gem 'webmock'
end
